# Nome da aplicação
spring.application.name=biblioteca

# Configurações de Conexão com o Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Como vamos usar o Flyway para criar as tabelas, o Hibernate só vai "validar"
spring.jpa.hibernate.ddl-auto=validate
# Mostra os comandos SQL no terminal (ótimo para debugar)
spring.jpa.show-sql=true

# Configuração do Flyway
spring.flyway.enabled=true